# Generated by Django 4.0.5 on 2022-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMTV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fantasia', models.CharField(max_length=40)),
                ('razon_social', models.CharField(max_length=40)),
                ('cuit', models.IntegerField()),
                ('direccion_nombre', models.CharField(max_length=40)),
                ('direccion_numero', models.IntegerField()),
                ('fecha_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=40)),
                ('fecha_pago', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fantasia', models.CharField(max_length=40)),
                ('razon_social', models.CharField(max_length=40)),
                ('cuit', models.IntegerField()),
                ('direccion_nombre', models.CharField(max_length=40)),
                ('direccion_numero', models.IntegerField()),
                ('fecha_alta', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
    ]
