# Generated by Django 4.0.5 on 2022-06-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMTV', '0002_articulos_clientes_pagos_proveedores_delete_familia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='direccion_numero',
            new_name='altura',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='direccion_nombre',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='nom_fantasia',
            new_name='nombre_fantasia',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='direccion_numero',
            new_name='altura',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='direccion_nombre',
            new_name='calle',
        ),
    ]
