# Generated by Django 4.0.5 on 2022-06-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMTV', '0003_rename_direccion_numero_clientes_altura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='nom_fantasia',
            new_name='nombre_fantasia',
        ),
    ]
